### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by perepujal** [comment]
Hi, thanks for the correction, and for reporting the issue.

I've just added the SourceForge bugtracker URL to the Readme, I am not inclined to have 2 separate bugtrackers, one at SF the other at github.

About the issue, this looks like a problem with SDL2, I guess the first attempt at correct it sould be to update the SDL2 version to the latest stable(2.0.14 at the time of this writing)
Currently this port  uses 2.0.12 from early 2020.

Thanks
Pere

**Comment by rubo77** [comment]
ok, so I will use https://sourceforge.net/p/tuxpaint/bugs/ then. (You should put it at the start of the readme)

Will you try to fix my issue? Do you need more information on my problem?

And I found another typo: "eithor" should be "either"

**Comment by perepujal** [comment]
Hi, could you test the 9256 apk from 2021 03 25 and report success or failure?
https://provant.freeddns.org/pere/public_html/developing/20210325/
It is  a devel build, so things are not fixed, but I've updated SDL2 and hopefully that fixes the screen problem
If it displays full screen, you may find the buttons very small, is a change that can be adjusted in the config utility.

Thanks
Pere

**Comment by rubo77** [comment]
great, thanks, that works ;)

**Comment by perepujal** [comment]
Hi, Thanks for testing and reporting.
Glad to see that the screen problem solved with an update of SDL2 :)
I guess we should provide a buildfix without the devel functionality for now.

About the lack of multifinger input, this is an old problem already present in 0.9.24 from mid last year, as I understand it, before, when multifinger input worked, tuxpaint got alternative events from each finger, currently it only gets the events of one finger :(
At the time I didn't found a quick solution :(

**Comment by perepujal** [comment]
Hi, sorry to bother you again,
Could I ask a favor? Could you please test the bugfix1 version? (it has not the devel stuff)
https://provant.freeddns.org/pere/public_html/0.9.25/bugfix1/
If the screen displays fine with it too, then it could be released for other people too :)
Thanks
Pere

**Comment by rubo77** [comment]
I tested it and sorry, no, that dedn't seem to fix the problem, I have the same screen in the corner again

**Comment by perepujal** [comment]
Thanks, 

So the fix was not the update of SDL2 but something else that has been done in the devel stuff(or the combination of both)
Thinking on it, the only thing that comes to my mind in the devel changes for the next version that could affect screen display is the removal of anyDensity=false in the AndroidManifest.xml file

Unfortunately this change depends on having button size resizable, otherwise buttons will end up very small, so it can't be integrated in a buildfix for 0.9.25, the only workaround I see is to use the preliminary devel build for the new version that you tested first.

Thanks again :)
Pere

**Comment by rubo77** [comment]
So did SDL change in Android 11?
It when did the error start?

**Comment by rubo77** [comment]
I tried the old 0.9.23 beta version, but there I have the same problem

**Comment by rubo77** [comment]
Maybe you could add a branch with minimal functionality, without menu, but so children just can paint with a fat red pen and with Multitouch?
That should be an easy fork

**Comment by billkendrick** [comment]
In case it's useful, someone on Twitter reported a similar issue on a Pixel device: https://twitter.com/whovian9369/status/1377008332746203137

**Comment by rubo77** [comment]
This is a duplicate to https://sourceforge.net/p/tuxpaint/bugs/231/

&TLDR; This version works fine: https://provant.freeddns.org/pere/public_html/0.9.26/rc1/org.tuxpaint_9257.apk

**Pull request merged**
