### PR TITLE
Adding support for arm64-v8a which Google Play requires

### PR DESCRIPTION
**Pull request by automaton82**
Currently Tux Paint Android only supports armeabi-v7a, 32-bit. However Google Play now (since August 1 2019) requires arm64-v8a to be supported -- https://developer.android.com/google/play/requirements/64-bit.

In order to support this I've made changes following the guidelines here https://developer.android.com/games/optimize/64-bit to allow cross-building. I built and test this on my S8+ and S22+, both of which are 64-bit and it appears to work fine.

Most of the issues involved implicit function usage.

It would be good to test on a physical 32-bit device as well as I can't even emulate it it seems.

I also had to change the package id (org.tuxpaint was already taken on the Play Store somehow) and set the version information.

### CODE REVIEW

**Comment by automaton82** [comment]
@perepujal would be great if you can test that these changes build fine in your own configurations as well. If you have any 32-bit device or emulator to test that would be good too, I don't have one.

The changes themselves should not touch the 32-bit version, but I was unable to verify in practice.

**Comment by perepujal** [comment]
Hi, 
Changes build fine here in my computer, and run fine in a 32 bit(Lineage 14.1 AKA Android 7) phone :)
Congrats :)
I wonder if we could recover the org.tuxpaint id to make use of it in the Play Store, apks distributed in Sourceforge, as well ones compiled and distributed by f-droid use the org.tuxpaint id.

**Comment by automaton82** [comment]
> Hi, Changes build fine here in my computer, and run fine in a 32 bit(Lineage 14.1 AKA Android 7) phone :) Congrats :) I wonder if we could recover the org.tuxpaint id to make use of it in the Play Store, apks distributed in Sourceforge, as well ones compiled and distributed by f-droid use the org.tuxpaint id.

Yes, it's a good point, with the applicationId change it's possible new installs will end up going side-by-side with the old app name.

Unfortunately I don't think there's any recovery process for the old application id. However, when I publish to the app store I generate a .aab file, and I don't think you would do that for the apk or f-droid. So perhaps the build.gradle can detect that I'm generating the aab file for release and change the application id so it doesn't affect existing installs.

I will take a look at that.

**Comment by automaton82** [comment]
Okay commit [d17639f](https://github.com/tux4kids/Tuxpaint-Android/pull/16/commits/d17639f3982ce58a84a562423c84770fce6ce807) deals with the application ID problem by using 2 build variant flavors. I build the `playStore` flavor for the Google Store, and anyone else can build `offPlayStore` for the apk / f-droid release to avoid disruption.

One thing I do not understand is this flag:
`def buildAsLibrary = project.hasProperty('BUILD_AS_LIBRARY')`

This `buildAsLibrary` flag is used all over the gradle but I don't see why anyone would ever want to build it like this. Do you happen to know why this stuff is here?

**Comment by perepujal** [comment]
The buildAsLibrary must be a leftover from the SDL2 android-project template, 
See app/src/main/jni/SDL2/android-project/app/build.gradle

Best

**Comment by automaton82** [comment]
> The buildAsLibrary must be a leftover from the SDL2 android-project template, See app/src/main/jni/SDL2/android-project/app/build.gradle
> 
> Best

Ah okay, then maybe I can remove it if nobody is building as a library anymore.

**Pull request merged**
