### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hugok79**
fix typo `pt-PT`

### CODE REVIEW

**Comment by hugok79** [comment]
@perepujal https://github.com/tux4kids/Tuxpaint-Android/tree/6a8899c419a6de1ff3f316a17a58b138657d44e4/app/src/main/res/values-pt-rPT

**Comment by hugok79** [comment]
@perepujal  typo in values-pt-rPT

**Comment by perepujal** [comment]
Hi Hugo, the only thing I can say is that with values-pt-rPT the translations work, and that with  values-pt-PT they do not work.
I don't know why, if there is some Android reason for adding the 'r' or what, but in the tests I did the 'r' is needed

Best
Pere

**Comment by hugok79** [comment]
Hi.,
I have no idea.... I just translate, I don't code. But I see that the Tradicional Chinese `zh_TW` language also have an "r" before TW.
I don't know if it has to do with the fact that the lang code is `pt_PT` instead of `pt` or the Brazilian Portuguese `pt_BR`

**Comment by hugok79** [comment]
Perhaps Bill Kendrick from Tux Paint can help?

**Comment by perepujal** [comment]
I found something that seems authoritative, from Android developers:
https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources
scroll a little down to the "Language, script (optional), and region (optional)" section:

"The language is defined by a two-letter [ISO 639-1](http://www.loc.gov/standards/iso639-2/php/code_list.php) language code, optionally followed by a two-letter [ISO 3166-1-alpha-2](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) region code (preceded by lowercase r)"

**Comment by hugok79** [comment]
Interesting. So it always has to do with the language/region code.

**Pull request closed without merging**
